baseURL: 'https://anna-damm.de/'
title: Anna Damm
languageCode: de-DE

disableKinds:
  - taxonomy
  - term

params:
  author: Anna Damm
  description: >-
    Anna Damm ist Teamleiterin der Software-Entwicklungsabteilung für Private Krankenkassen
    bei CHECK24
  avatar: img/profile.jpg

  social:
    LinkedIn: anna-damm-645b3431
    Github: AnnaDamm
    Stackoverflow: 1386610/Arany
    Email: anna.damm87@googlemail.com
